# -*- coding: utf-8 -*-
"""Content model for the Универмаг «Россия» static storefront."""

BRAND = {
    "name": "Универмаг «Россия»",
    "center": "Национальный центр «Россия»",
    "center_url": "https://russia.ru/",
    "footer_project": "",
    "tagline": "Официальный интернет-магазин одежды и мерча Национального центра «Россия»",
    "address": "Москва, территория ВДНХ, павильон Национального центра «Россия»",
    "email": "shop@rossiya-centre.ru",
    "phone": "+7 (495) 000-00-00",
    "domain": "shop.russia.ru",
}

# Цитата ФС (гайд-драфт ФРК): акцент только на «Россия», длинное тире — под словом.
BRAND_QUOTE = {
    "before": "Для меня",
    "accent": "Россия",
    "after": "вся моя жизнь",
}

# Референсные фото (CDN gloryseason.ru) — замена битых Unsplash.
REF = {
    "polo": "https://thb.tildacdn.com/tild6135-3439-4533-a632-356233303737/-/resize/800x/333.jpg",
    "longsliv": "https://thb.tildacdn.com/tild3466-6234-4739-b031-323831666135/-/resize/800x/2.jpg",
    "winter": "https://thb.tildacdn.com/tild3764-3665-4936-a664-336234313838/-/resize/800x/1.jpg",
    "winter_lg": "https://thb.tildacdn.com/tild3764-3665-4936-a664-336234313838/-/resize/1200x/1.jpg",
    "lifestyle": "https://thb.tildacdn.com/tild3662-6136-4236-a361-653666623865/-/resize/1200x/1680x1120.jpg",
    "gift": "https://static.tildacdn.com/tild3637-3734-4539-a632-373961663536/321.png",
    "accessory": "https://thb.tildacdn.com/tild6334-3261-4564-a630-343364643761/-/resize/800x/999999.jpg",
}

# Ассортимент и формулировки — по структуре putin-team.ru / gloryseason.ru, без чужих брендов и названий.
PRODUCTS = [
    {
        "slug": "futbolka-oranzhevaya",
        "title": "Футболка «Оранжевая линия»",
        "cat": "futbolki",
        "cat_label": "Футболки",
        "collection": "Russia Capsule",
        "gender": "Унисекс",
        "price": 3990,
        "old": 4590,
        "tag": "Новинка",
        "colors": ["белый", "чёрный"],
        "img": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
        "short": "Плотный хлопок 220 г/м², прямой крой. Принт с архитектурным мотивом фасада.",
        "long": "Модель из капсулы Russia Capsule — для гостей центра и города. Мягкая ткань, стойкий принт, аккуратная обработка швов. Спокойный официальный тон без провокационных акцентов.",
        "composition": "80% хлопок, 20% полиэстер",
        "care": "Стирка при 30 °C, не отбеливать",
    },
    {
        "slug": "futbolka-belaya",
        "title": "Футболка «Белый фасад»",
        "cat": "futbolki",
        "cat_label": "Футболки",
        "collection": "Базовая линейка",
        "gender": "Унисекс",
        "price": 3490,
        "old": None,
        "tag": "Хит",
        "colors": ["белый"],
        "img": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80",
        "short": "Базовая футболка с минималистичной вышивкой. Посадка regular fit.",
        "long": "Базовая модель для повседневной покупки: нейтральный цвет, лаконичный брендинг, понятная цена входа.",
        "composition": "100% хлопок, 180 г/м²",
        "care": "Стирка при 30 °C, гладить с изнанки",
    },
    {
        "slug": "futbolka-zhenskaya-rose",
        "title": "Футболка женская «Розовый закат»",
        "cat": "futbolki",
        "cat_label": "Футболки",
        "collection": "Женская линия",
        "gender": "Женское",
        "price": 3790,
        "old": None,
        "tag": "Женское",
        "colors": ["розовый", "белый"],
        "img": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
        "short": "Приталенный силуэт, мягкий принт на груди.",
        "long": "Отдельная женская линия без перегруза каталога. Комфортная посадка на весь день.",
        "composition": "95% хлопок, 5% эластан",
        "care": "Деликатная стирка при 30 °C",
    },
    {
        "slug": "futbolka-polo-klassik",
        "title": "Поло «Классика центра»",
        "cat": "futbolki",
        "cat_label": "Футболки",
        "collection": "Базовая линейка",
        "gender": "Мужское",
        "price": 4290,
        "old": None,
        "tag": "Новинка",
        "colors": ["тёмно-зелёный", "белый"],
        "img": REF["polo"],
        "short": "Поло с воротником и пуговицами, вышивка герба на груди.",
        "long": "Классическая посадочная категория «поло» — аккуратный дресс-код для мероприятий и повседневного гардероба.",
        "composition": "100% хлопок пике",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "futbolka-oversize-fasad",
        "title": "Футболка oversize «Фасад»",
        "cat": "futbolki",
        "cat_label": "Футболки",
        "collection": "Russia Capsule",
        "gender": "Унисекс",
        "price": 4190,
        "old": None,
        "tag": "Oversize",
        "colors": ["чёрный", "молочный"],
        "img": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
        "short": "Свободный крой, крупная типографика «Россия» на спине.",
        "long": "Молодежная линия в рамках брифа: современный силуэт без провокационных сообщений.",
        "composition": "100% хлопок, 200 г/м²",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "futbolka-detskaya-centr",
        "title": "Футболка детская «Гость центра»",
        "cat": "futbolki",
        "cat_label": "Футболки",
        "collection": "Базовая линейка",
        "gender": "Детское",
        "price": 2990,
        "old": None,
        "tag": "Детское",
        "colors": ["белый", "зелёный"],
        "img": REF["polo"],
        "short": "Размеры 104–152, мягкий хлопок, принт с гербом.",
        "long": "Семейный сценарий покупки после визита на ВДНХ. Удобная посадка и гипоаллергенные красители.",
        "composition": "100% хлопок",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "longsliv-grafika",
        "title": "Лонгслив «Графика центра»",
        "cat": "longslivy",
        "cat_label": "Лонгсливы",
        "collection": "Russia Capsule",
        "gender": "Унисекс",
        "price": 4490,
        "old": None,
        "tag": "Новинка",
        "colors": ["чёрный", "серый"],
        "img": "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=800&q=80",
        "short": "Мягкий хлопок, графика центра, плотная посадка по плечу.",
        "long": "Базовый слой для прохладной погоды с официальным характером и читаемой символикой.",
        "composition": "92% хлопок, 8% эластан",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "longsliv-minimal",
        "title": "Лонгслив «Минимал»",
        "cat": "longslivy",
        "cat_label": "Лонгсливы",
        "collection": "Базовая линейка",
        "gender": "Унисекс",
        "price": 3990,
        "old": None,
        "tag": "Хит",
        "colors": ["молочный", "тёмно-зелёный"],
        "img": REF["longsliv"],
        "short": "Лаконичная вышивка, гладкое плетение.",
        "long": "Универсальный лонгслив для слоистых образов и корпоративных заказов.",
        "composition": "95% хлопок, 5% эластан",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "longsliv-zhenskij",
        "title": "Лонгслив женский «Линия»",
        "cat": "longslivy",
        "cat_label": "Лонгсливы",
        "collection": "Женская линия",
        "gender": "Женское",
        "price": 4290,
        "old": None,
        "tag": "Женское",
        "colors": ["бордовый", "чёрный"],
        "img": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
        "short": "Удлинённый крой, мягкий трикотаж.",
        "long": "Женская посадочная в категории лонгсливов — отдельный SKU в фильтрах каталога.",
        "composition": "92% хлопок, 8% эластан",
        "care": "Деликатная стирка",
    },
    {
        "slug": "svitshot-klassika",
        "title": "Свитшот «Классика»",
        "cat": "svitshoty",
        "cat_label": "Свитшоты и худи",
        "collection": "Базовая линейка",
        "gender": "Унисекс",
        "price": 5990,
        "old": None,
        "tag": "Хит",
        "colors": ["серый", "тёмно-зелёный"],
        "img": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
        "short": "Футер с мягким внутренним слоем, вышивка на груди.",
        "long": "Тёплый свитшот — ключевой кластер мерч-магазина с нейтральным официальным позиционированием.",
        "composition": "80% хлопок, 20% полиэстер",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "svitshot-premium",
        "title": "Худи «Премиум капсула»",
        "cat": "svitshoty",
        "cat_label": "Свитшоты и худи",
        "collection": "Russia Capsule",
        "gender": "Унисекс",
        "price": 7490,
        "old": 8200,
        "tag": "−9%",
        "colors": ["чёрный", "молочный"],
        "img": "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80",
        "short": "Оверсайз, капюшон, плотный материал.",
        "long": "Премиальная верхняя категория: отдельный визуал капсулы и более высокий средний чек.",
        "composition": "85% хлопок, 15% полиэстер",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "khudi-molniya-trikolor",
        "title": "Худи на молнии «Триколор»",
        "cat": "svitshoty",
        "cat_label": "Свитшоты и худи",
        "collection": "Базовая линейка",
        "gender": "Мужское",
        "price": 6990,
        "old": None,
        "tag": "Новинка",
        "colors": ["синий", "белый", "красный"],
        "img": REF["longsliv"],
        "short": "Молния по центру, контрастные вставки, вышивка.",
        "long": "Популярный силуэт «толстовка на молнии» — удобный слой для прохладной погоды и поездок.",
        "composition": "80% хлопок, 20% полиэстер",
        "care": "Стирка при 30 °C, застёжку закрыть",
    },
    {
        "slug": "tolstovka-futer",
        "title": "Толстовка «Футер»",
        "cat": "svitshoty",
        "cat_label": "Свитшоты и худи",
        "collection": "Зимняя линейка 2026",
        "gender": "Унисекс",
        "price": 5490,
        "old": None,
        "tag": "Зима",
        "colors": ["тёмно-зелёный", "чёрный"],
        "img": REF["longsliv"],
        "short": "Классический крой без капюшона, утеплённый футер.",
        "long": "Свитшот без капюшона — отдельный спрос в категории «худи / толстовки» на старте каталога.",
        "composition": "80% хлопок, 20% полиэстер, флис",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "sport-kostyum-rossiya",
        "title": "Спортивный костюм «Россия»",
        "cat": "kostyumy",
        "cat_label": "Спортивные костюмы",
        "collection": "Комфорт",
        "gender": "Унисекс",
        "price": 9990,
        "old": None,
        "tag": "Новинка",
        "colors": ["тёмно-зелёный"],
        "img": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80",
        "short": "Худи и брюки, логотип на груди.",
        "long": "Комфортный городской сегмент с официальной символикой для поездок и прогулок.",
        "composition": "70% хлопок, 30% полиэстер",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "kostyum-zhenskij-comfort",
        "title": "Костюм женский «Комфорт»",
        "cat": "kostyumy",
        "cat_label": "Спортивные костюмы",
        "collection": "Женская линия",
        "gender": "Женское",
        "price": 9490,
        "old": 10490,
        "tag": "−10%",
        "colors": ["серый", "молочный"],
        "img": "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80",
        "short": "Кофта и брюки, мягкий трикотаж.",
        "long": "Женский спортивный комплект — отдельная витрина в категории костюмов.",
        "composition": "75% хлопок, 25% полиэстер",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "kepka-simvol",
        "title": "Кепка «Символ»",
        "cat": "kepki",
        "cat_label": "Кепки и аксессуары",
        "collection": "Аксессуары",
        "gender": "Унисекс",
        "price": 2490,
        "old": None,
        "tag": "Аксессуар",
        "colors": ["тёмно-зелёный", "чёрный"],
        "img": REF["accessory"],
        "short": "Вышивка, регулировка, хлопок twill.",
        "long": "Аксессуарный вход в бренд с невысоким чеком.",
        "composition": "100% хлопок",
        "care": "Ручная стирка",
    },
    {
        "slug": "shapka-teremok",
        "title": "Шапка «Теремок»",
        "cat": "kepki",
        "cat_label": "Кепки и аксессуары",
        "collection": "Зимняя линейка 2026",
        "gender": "Унисекс",
        "price": 2790,
        "old": None,
        "tag": "Зима",
        "colors": ["тёмно-зелёный", "бежевый"],
        "img": REF["accessory"],
        "short": "Вязаная шапка с вышивкой, утеплённая подкладка.",
        "long": "Зимний аксессуарный SKU для комплекта с куртками и свитшотами.",
        "composition": "50% шерсть, 50% акрил",
        "care": "Ручная стирка",
    },
    {
        "slug": "sharf-zimnij",
        "title": "Шарф «Зимний центр»",
        "cat": "kepki",
        "cat_label": "Кепки и аксессуары",
        "collection": "Зимняя линейка 2026",
        "gender": "Унисекс",
        "price": 3290,
        "old": None,
        "tag": "Подарок",
        "colors": ["зелёный", "золотой"],
        "img": REF["accessory"],
        "short": "Мягкий шерстяной шарф, фирменная бирка.",
        "long": "Подарочный аксессуар с фирменной лентой красного, зелёного или белого цвета.",
        "composition": "100% акрил",
        "care": "Ручная стирка",
    },
    {
        "slug": "sumka-shopper",
        "title": "Шоппер «Национальный центр»",
        "cat": "sumki",
        "cat_label": "Сумки",
        "collection": "Аксессуары",
        "gender": "Унисекс",
        "price": 1990,
        "old": None,
        "tag": "Подарок",
        "colors": ["крафт"],
        "img": REF["gift"],
        "short": "Крафт-пакет с зелёным покрытием и золотым логотипом.",
        "long": "Шоппер по гайдбуку упаковки: крафт, фирменные цвета Pantone 4216 и 871.",
        "composition": "100% хлопок, 320 г/м²",
        "care": "Стирка при 30 °C",
    },
    {
        "slug": "ryukzak-gorod",
        "title": "Рюкзак «Город»",
        "cat": "sumki",
        "cat_label": "Сумки",
        "collection": "Аксессуары",
        "gender": "Унисекс",
        "price": 4490,
        "old": None,
        "tag": "Новинка",
        "colors": ["тёмно-зелёный"],
        "img": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
        "short": "Городской рюкзак, отделение для ноутбука 13″.",
        "long": "Практичный аксессуар для поездок на мероприятия центра.",
        "composition": "полиэстер, подкладка хлопок",
        "care": "Влажная чистка",
    },
    {
        "slug": "kurtka-veter",
        "title": "Куртка «Ветер с севера»",
        "cat": "kurtki",
        "cat_label": "Верхняя одежда",
        "collection": "Russia Capsule",
        "gender": "Унисекс",
        "price": 12990,
        "old": None,
        "tag": "Премиум",
        "colors": ["тёмно-синий", "чёрный"],
        "img": "https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=800&q=80",
        "short": "Ветровка с капюшоном, водоотталкивающая пропитка.",
        "long": "Urban outerwear с брендингом центра — верхняя одежда премиального сегмента.",
        "composition": "100% полиэстер",
        "care": "Химчистка или деликатная стирка",
    },
    {
        "slug": "kurtka-puhovik",
        "title": "Пуховик «Север»",
        "cat": "kurtki",
        "cat_label": "Верхняя одежда",
        "collection": "Зимняя линейка 2026",
        "gender": "Унисекс",
        "price": 15990,
        "old": 17990,
        "tag": "Зима",
        "colors": ["чёрный", "оливковый"],
        "img": REF["winter"],
        "short": "Утеплённый пуховик, капюшон, лёгкий наполнитель.",
        "long": "Категория «пуховики» — сезонный спрос и подарочные покупки к зиме.",
        "composition": "верх: полиэстер, наполнитель: синтепон",
        "care": "Химчистка",
    },
    {
        "slug": "bomber-fluffy",
        "title": "Бомбер «Объём»",
        "cat": "kurtki",
        "cat_label": "Верхняя одежда",
        "collection": "Russia Capsule",
        "gender": "Унисекс",
        "price": 11490,
        "old": None,
        "tag": "Новинка",
        "colors": ["молочный", "чёрный", "оливковый"],
        "img": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&q=80",
        "short": "Укороченный бомбер, мягкий утеплитель, три расцветки.",
        "long": "Современный силуэт верхней одежды — отдельная карточка в SEO-кластере «куртки / бомберы».",
        "composition": "полиэстер, синтепон",
        "care": "Химчистка",
    },
    {
        "slug": "parka-zimnyaya",
        "title": "Парка «ВДНХ»",
        "cat": "kurtki",
        "cat_label": "Верхняя одежда",
        "collection": "Зимняя линейка 2026",
        "gender": "Унисекс",
        "price": 14990,
        "old": None,
        "tag": "Зима",
        "colors": ["тёмно-зелёный"],
        "img": REF["winter"],
        "short": "Удлинённая парка, меховая отделка капюшона.",
        "long": "Тёплая верхняя одежда для гостей центра в холодный сезон.",
        "composition": "мембрана, утеплитель",
        "care": "Химчистка",
    },
    {
        "slug": "podarochnyj-nabor",
        "title": "Подарочный набор «Старт»",
        "cat": "podarki",
        "cat_label": "Подарки",
        "collection": "Подарочные наборы",
        "gender": "Унисекс",
        "price": 5490,
        "old": 6200,
        "tag": "Набор",
        "colors": [],
        "img": REF["gift"],
        "short": "Футболка + шоппер + открытка в фирменной упаковке.",
        "long": "Готовый набор для корпоративных и личных подарков с символикой России.",
        "composition": "Состав по вложенным SKU",
        "care": "См. карточки товаров в наборе",
    },
    {
        "slug": "mystery-box",
        "title": "Mystery Box",
        "cat": "podarki",
        "cat_label": "Подарки",
        "collection": "Mystery Box",
        "gender": "Унисекс",
        "price": 4990,
        "old": 7990,
        "tag": "−38%",
        "colors": [],
        "img": REF["accessory"],
        "short": "2–3 вещи из прошлых коллекций, выберите размер.",
        "long": "Сюрприз-набор по фиксированной цене. Состав не раскрывается заранее; возврат по правилам магазина.",
        "composition": "Состав набора варьируется",
        "care": "См. бирки вложений",
    },
    {
        "slug": "podarochnyj-sertifikat",
        "title": "Электронный подарочный сертификат",
        "cat": "podarki",
        "cat_label": "Подарки",
        "collection": "Подарочные наборы",
        "gender": "Унисекс",
        "price": 5000,
        "old": None,
        "tag": "Сертификат",
        "colors": [],
        "img": REF["accessory"],
        "short": "Номинал от 3 000 до 15 000 ₽, отправка на email.",
        "long": "Подарочный сценарий из SEO-кластера «сертификат / подарок» — без выбора размера.",
        "composition": "—",
        "care": "—",
    },
]

for product in PRODUCTS:
    product["img"] = f"/assets/generated/products/{product['slug']}.jpg"

PRODUCT_CATEGORY_OVERRIDES = {
    "longsliv-grafika": ("svitshoty", "Свитшоты"),
    "longsliv-minimal": ("svitshoty", "Свитшоты"),
    "longsliv-zhenskij": ("svitshoty", "Свитшоты"),
    "svitshot-klassika": ("svitshoty", "Свитшоты"),
    "svitshot-premium": ("hudi", "Худи"),
    "khudi-molniya-trikolor": ("hudi", "Худи"),
    "tolstovka-futer": ("svitshoty", "Свитшоты"),
    "sport-kostyum-rossiya": ("hudi", "Худи"),
    "kostyum-zhenskij-comfort": ("svitshoty", "Свитшоты"),
    "kepka-simvol": ("aksessuary", "Аксессуары"),
    "shapka-teremok": ("aksessuary", "Аксессуары"),
    "sharf-zimnij": ("aksessuary", "Аксессуары"),
    "sumka-shopper": ("aksessuary", "Аксессуары"),
    "ryukzak-gorod": ("aksessuary", "Аксессуары"),
    "kurtka-veter": ("vetrovki", "Ветровки"),
    "kurtka-puhovik": ("kurtki", "Куртки"),
    "bomber-fluffy": ("kurtki", "Куртки"),
    "parka-zimnyaya": ("kurtki", "Куртки"),
    "podarochnyj-nabor": ("aksessuary", "Аксессуары"),
    "mystery-box": ("aksessuary", "Аксессуары"),
    "podarochnyj-sertifikat": ("aksessuary", "Аксессуары"),
}

for product in PRODUCTS:
    if product["slug"] in PRODUCT_CATEGORY_OVERRIDES:
        product["cat"], product["cat_label"] = PRODUCT_CATEGORY_OVERRIDES[product["slug"]]

PRODUCT_SUBCATEGORY_OVERRIDES = {
    "longsliv-grafika": "Без флиса",
    "longsliv-minimal": "Без флиса",
    "longsliv-zhenskij": "Без флиса",
    "svitshot-klassika": "Без флиса",
    "kostyum-zhenskij-comfort": "Без флиса",
    "tolstovka-futer": "С флисом",
}

for product in PRODUCTS:
    product["subcat"] = PRODUCT_SUBCATEGORY_OVERRIDES.get(product["slug"], "")

CATEGORIES = [
    (
        "hudi",
        "Худи",
        "Купить худи Универмага «Россия» — плотные модели с капюшоном, молнией и спокойной фирменной графикой. Доставка СДЭК или Яндекс по России.",
    ),
    (
        "svitshoty",
        "Свитшоты",
        "Свитшоты Универмага «Россия» — единая категория с фильтрами «с флисом» и «без флиса», размеры S–3XL, оплата сразу или при получении.",
    ),
    (
        "futbolki",
        "Футболки",
        "Купить футболки с символикой Национального центра «Россия» — базовые модели, поло, oversize и детская линия. Доставка по России.",
    ),
    (
        "vetrovki",
        "Ветровки",
        "Ветровки Универмага «Россия» — лёгкая верхняя одежда с капюшоном, водоотталкивающей тканью и фирменной сдержанной подачей.",
    ),
    (
        "kurtki",
        "Куртки",
        "Куртки Универмага «Россия» — пуховики, бомберы и парки для холодного сезона, размеры S–3XL, доставка по России.",
    ),
    (
        "aksessuary",
        "Аксессуары",
        "Аксессуары Универмага «Россия»: кепки, шапки, значки, книги, шоперы, детские игры и электронные подарочные сертификаты.",
    ),
]

COLLECTIONS = [
    {
        "slug": "russia-capsule",
        "title": "Единая партия",
        "lead": "Товары отшиваются партиями под запрос заказчика: без отдельной коллекционной логики.",
        "story": "В основе каталога — простые категории: футболки, свитшоты, худи, верхняя одежда и аксессуары.",
        "img": "/assets/generated/products/svitshot-premium.jpg",
    },
    {
        "slug": "mystery-box",
        "title": "Подарочные сценарии",
        "lead": "Электронные сертификаты и наборы для покупки без выбора конкретного размера.",
        "story": "Сертификат можно оформить на сайте; наборы помогают закрыть подарочный сценарий без лишнего выбора.",
        "img": "/assets/generated/products/podarochnyj-sertifikat.jpg",
    },
    {
        "slug": "zimnyaya-liniya",
        "title": "Одежда и аксессуары",
        "lead": "Единая витрина для худи, свитшотов, футболок, ветровок, курток, кепок, шапок, значков, книг, шоперов и детских игр.",
        "story": "Покупатель сразу видит категории, визуализацию, выбирает товар, добавляет в корзину и оплачивает.",
        "img": "/assets/generated/products/kurtka-veter.jpg",
    },
]

# Главный экран: «разбитое» hero-фото (презентация референсов клиента)
HERO_MOSAIC_SLUGS = [
    "futbolka-oranzhevaya",
    "kurtka-veter",
    "svitshot-premium",
    "longsliv-grafika",
]

# Редакционный блок «мерч на моделях» (плейсхолдеры до фотосессии)
EDITORIAL_SHOTS = [
    {
        "img": "/assets/generated/products/sport-kostyum-rossiya.jpg",
        "title": "Посадка",
        "href": "sizes/",
    },
    {
        "img": "/assets/generated/products/kurtka-puhovik.jpg",
        "title": "Материалы",
        "href": "catalog/kurtki/",
    },
    {
        "img": "/assets/generated/products/futbolka-oranzhevaya.jpg",
        "title": "Цитаты",
        "href": "catalog/futbolki/",
    },
]

BLOG_POSTS = [
    {
        "slug": "kak-vybrat-razmer",
        "title": "Как выбрать размер: футболки и свитшоты",
        "excerpt": "Таблица размеров, советы по посадке regular и oversize.",
        "img": "https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=800&q=80",
        "body": "Размер — частый вопрос для интернет-магазина одежды. Мы выносим гид в журнал и дублируем таблицу в карточках товаров.",
    },
    {
        "slug": "podarki-s-simvolikoj",
        "title": "Подарки с символикой России: гид 2026",
        "excerpt": "Наборы, сертификаты и идеи до 5 000 ₽.",
        "img": "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=800&q=80",
        "body": "Объединяем сертификаты, подборки и коллекционные истории в понятный подарочный сценарий.",
    },
    {
        "slug": "istoriya-russia-capsule",
        "title": "История коллекции Russia Capsule",
        "excerpt": "Как мы собирали визуал капсулы и почему архитектура центра стала ключевым мотивом.",
        "img": "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=800&q=80",
        "body": "Контент для SEO-кластера «коллекция одежды» и перелинковки с каталогом.",
    },
]
